import { expect, Page, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function onboard(page:Page,name='Sunny'):Promise<void>{await page.goto('/');await page.getByRole('button',{name:'Let’s get started'}).click();await page.getByRole('textbox').fill(name);await page.getByRole('button',{name:'Continue',exact:false}).click();await page.getByRole('button',{name:'Start my adventure'}).click();await expect(page.getByRole('heading',{name:`Hello, ${name}!`})).toBeVisible();}
async function gate(page:Page):Promise<void>{await page.goto('/parent');const challenge=await page.locator('.challenge').innerText();const numbers=challenge.match(/\d+/g)?.map(Number)??[];await page.getByRole('spinbutton').fill(String(numbers[0]*numbers[1]));await page.getByRole('button',{name:'Enter Parent Zone'}).click();await expect(page.getByRole('heading',{name:'A window into their world'})).toBeVisible();}
test('complete learning flow, gentle retry, stars and persisted progress',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await onboard(page);await page.locator('app-category-card').filter({hasText:'Animals'}).click();await page.getByRole('link',{name:'Elephant',exact:false}).click();await page.getByRole('button',{name:'Listen again'}).click();await page.getByRole('link',{name:'Let’s find it!'}).click();await expect(page.getByRole('heading',{name:'Can you find Elephant?'})).toBeVisible();const wrong=page.locator('.answer-card').filter({hasNotText:'Elephant'}).first();await wrong.click();await expect(page.getByText('Almost! Let’s try again.')).toBeVisible();await page.getByRole('button',{name:'Elephant',exact:true}).click();await expect(page.locator('.feedback')).toHaveText('You found it! Wonderful!');await page.reload();await page.goto('/rewards');await expect(page.locator('.star-collection>strong')).toHaveText('1');await gate(page);await expect(page.locator('.category-progress-row').filter({hasText:'Animals'})).toContainText('1 / 16');await expect(page.locator('.stats-grid .panel').nth(2).locator('strong')).toHaveText('0');expect(errors).toEqual([]);
});
test('English and Hindi profile preferences, protected settings and profile isolation',async({page})=>{
 await onboard(page);await page.goto('/parent/settings');await expect(page.getByRole('heading',{name:'Hello, grown-up!'})).toBeVisible();await gate(page);await page.getByRole('link',{name:'Little learners',exact:true}).click();await page.getByRole('link',{name:'Add a little learner'}).click();await page.getByRole('textbox').fill('Tara');await page.getByRole('button',{name:'Continue',exact:false}).click();await page.getByRole('button',{name:'हिन्दी',exact:true}).click();await page.getByRole('button',{name:'मेरा सफ़र शुरू करें'}).click();await expect(page.getByRole('heading',{name:'नमस्ते, Tara!'})).toBeVisible();await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','hi');await page.goto('/learn/animals/elephant');await expect(page.getByRole('heading',{name:'हाथी',exact:true})).toBeVisible();await page.goto('/rewards');await expect(page.locator('.star-collection>strong')).toHaveText('0');
});
test('all four games can finish and memory pairs are accessible',async({page})=>{
 await onboard(page);
 for(const kind of ['find-it','match','count']){await page.goto('/play/'+kind);for(let n=0;n<5;n++){await expect(page.locator('.answer-card').first()).toBeVisible();const options=page.locator('.answer-card');const count=await options.count();for(let k=0;k<count;k++){await options.nth(k).click();await expect(page.locator('.feedback')).toBeVisible();if((await page.locator('.feedback').innerText()).includes('Wonderful'))break;}await page.getByRole('button',{name:'Keep exploring'}).click();}await expect(page.getByRole('heading',{name:'Look what you did!'})).toBeVisible();}
 await page.goto('/play/memory');const cards=page.locator('.memory-card');const found=new Map<string,number>();while(!(await page.locator('.result').count())){let paired=false;for(let n=0;n<4;n++){if(await cards.nth(n).isDisabled())continue;await cards.nth(n).click();const label=await cards.nth(n).getAttribute('aria-label');if(label){const prior=found.get(label);if(prior!==undefined && prior!==n && !(await cards.nth(prior).isDisabled())){await cards.nth(prior).click();paired=true;break;}found.set(label,n);}if(await page.locator('.memory-card.face-up:not(.matched)').count()===2)await page.waitForTimeout(1300);}if(!paired)await page.waitForTimeout(1300);}await expect(page.getByRole('heading',{name:'Look what you did!'})).toBeVisible();
});
test('offline reload reaches uncached routes and Hindi content',async({page,context})=>{
 await onboard(page);await page.evaluate(async()=>{const registration=await navigator.serviceWorker.ready;if(!registration.active)throw new Error('No active service worker');});await page.reload();await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);await context.setOffline(true);await page.goto('/learn/fruits');await expect(page.locator('a[href="/learn/fruits/apple"]')).toBeVisible();await page.goto('/learn/animals/elephant');await expect(page.getByRole('heading',{name:'Elephant',exact:true})).toBeVisible();await expect(page.getByText('You’re offline. Let’s keep learning!')).toBeVisible();const hi=await page.evaluate(async()=>{const r=await fetch('/assets/content/hi/animals.json');return r.ok;});expect(hi).toBe(true);
});
test('responsive layouts, keyboard access and accessibility',async({page},testInfo)=>{
 await onboard(page);for(const route of ['/','/learn','/learn/animals','/learn/animals/elephant','/play','/play/find-it','/rewards','/parent/gate','/trace']){await page.goto(route);await expect(page.locator('main h1').first()).toBeVisible();await page.waitForTimeout(400);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),`${route}: ${JSON.stringify(results.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))}`).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}await page.goto('/');await page.screenshot({path:`test-results/home-${testInfo.project.name}.png`,fullPage:true});if(testInfo.project.name==='mobile'){await page.setViewportSize({width:320,height:720});await page.screenshot({path:'test-results/home-320.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
});
