import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { I18nService } from '../../core/i18n/i18n.service';
import { ProgressService } from '../../core/progress/progress.service';
@Component({ changeDetection: ChangeDetectionStrategy.OnPush, template: `
<div class="page"><div class="page-heading"><div><span class="eyebrow">{{i.t('nav.rewards')}}</span><h1>{{i.t('rewards.title')}}</h1><p>{{i.t('rewards.subtitle')}}</p></div></div><section class="star-collection"><div class="big-star" aria-hidden="true">★<span>✦</span></div><strong>{{progress.data().stars}}</strong><h2>{{i.t('rewards.total')}}</h2><p>{{i.t('rewards.note')}}</p></section><div class="section-title"><h2>{{i.t('rewards.badges')}}</h2></div><div class="badges">@for(badge of badges();track badge.id){<section class="badge panel" [class.unlocked]="badge.unlocked"><span class="badge-medal" aria-hidden="true">{{badge.icon}}</span><h3>{{i.t('rewards.'+badge.id)}}</h3><p>{{i.t('rewards.'+badge.id+'Desc')}}</p><span class="badge-status">{{i.t(badge.unlocked?'rewards.unlocked':'rewards.locked')}}</span></section>}</div></div>
`, styles:[`.page-heading .eyebrow{display:block;margin-bottom:10px}.star-collection{text-align:center;border-radius:28px;background:#f8efd9;padding:30px;margin-bottom:35px;position:relative;overflow:hidden}.big-star{font-size:5rem;color:#d9ae51;position:relative;display:inline-block;filter:drop-shadow(0 5px 0 #b7843320)}.big-star>span{position:absolute;font-size:2rem;right:-35px;top:8px}.star-collection>strong{display:block;font-size:3rem;color:#8a682f;margin:5px 0 12px}.star-collection h2{font-size:1.2rem}.star-collection p{font-size:.8rem;color:#82714e;margin-top:13px}.badges{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.badge{text-align:center;display:flex;align-items:center;flex-direction:column;padding:25px 17px;min-height:265px;background:#f5f2ef}.badge.unlocked{background:var(--paper)}.badge-medal{font-size:3.5rem;display:grid;place-items:center;width:90px;height:90px;background:#e7e1dc;border-radius:50%;filter:grayscale(1);opacity:.7;margin-bottom:20px}.unlocked .badge-medal{background:#f9edc9;filter:none;opacity:1}.badge h3{font-size:.95rem}.badge p{font-size:.74rem;color:var(--muted);margin-top:9px;line-height:1.6}.badge-status{font-size:.67rem;border-radius:20px;padding:7px 12px;background:#eae4df;margin-top:auto;position:relative;top:8px}.unlocked .badge-status{background:#e8f1e3;color:#476b43}@media(max-width:1100px){.badges{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.badges{gap:12px}.badge{padding:22px 12px}.badge h3{font-size:.85rem}.badge p{font-size:.68rem}.star-collection{padding:25px 18px}}`] })
export class RewardsComponent {
  readonly i=inject(I18nService);readonly progress=inject(ProgressService);
  readonly badges=computed(()=>[{id:'first',icon:'🌱',unlocked:this.progress.concepts().length>0},{id:'ten',icon:'🧭',unlocked:this.progress.data().activities.length>=10},{id:'fifty',icon:'⭐',unlocked:this.progress.data().stars>=50},{id:'animal',icon:'🐻',unlocked:this.progress.concepts().filter(c=>c.category==='animals').length>=8}]);
}
